Repository aidee-health/embody-file, pull requests merged in 2022-11, with the labels that each got.

#5 Prepare first public release
  .github/workflows/codeql.yml
  .github/workflows/release.yml
  README.md
  poetry.lock
  pyproject.toml
Labels: documentation, enhancement, dependencies

#12 Bump release to 1.0.2
  poetry.lock
  pyproject.toml
Labels: build, dependencies

#13 Upgrade embody codec to 1.0.11
  .github/workflows/release.yml
  .github/workflows/tests.yml
  docs/codeofconduct.md
  docs/contributing.md
  noxfile.py
  poetry.lock
  pyproject.toml
Labels: enhancement, dependencies

#16 Ignore missing IMU data
  pyproject.toml
  src/embodyfile/embodyfile.py
Labels: enhancement
